title: "Les guides pour les nuls"
description: "A compilation of theory that engineers are always forgetting."

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

nav_pages:
  - math.md
  - physics.md
  - algorithms.md